# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jgasparo <jgasparo@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/04/12 11:07:53 by jgasparo          #+#    #+#              #
#    Updated: 2023/04/26 11:36:12 by jgasparo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = libft.a

SRC = ft_atoi.c \
ft_bzero.c \
ft_calloc.c \
ft_isalnum.c \
ft_isalpha.c \
ft_isascii.c \
ft_isdigit.c \
ft_isprint.c \
ft_memchr.c \
ft_memcmp.c \
ft_memcpy.c \
ft_memmove.c \
ft_memset.c \
ft_putchar_fd.c \
ft_putendl_fd.c \
ft_putnbr_fd.c \
ft_putstr_fd.c \
ft_strchr.c \
ft_strdup.c \
ft_strjoin.c \
ft_strlcat.c \
ft_strlcpy.c \
ft_strlen.c \
ft_strmapi.c \
ft_strncmp.c \
ft_strnstr.c \
ft_strrchr.c \
ft_strtrim.c \
ft_substr.c \
ft_tolower.c \
ft_toupper.c \
ft_striteri.c \
ft_split.c \
ft_itoa.c \

SRC_B = ft_lstnew_bonus.c \
ft_lstsize_bonus.c \
ft_lstlast_bonus.c \
ft_lstadd_front_bonus.c \
ft_lstadd_back_bonus.c \
ft_lstdelone_bonus.c \
ft_lstclear_bonus.c \
ft_lstmap_bonus.c \
ft_lstiter_bonus.c \

OBJ = ${SRC:.c=.o}

OBJ_B = ${SRC_B:.c=.o}

CFLAGS = -Wall -Werror -Wextra

LIB  = ar rcs $(NAME) 

REMOVE = rm -f

all: $(NAME)

$(NAME):	$(OBJ)
	$(LIB) $(OBJ)

bonus: $(OBJ_B)
	$(LIB) $(NAME) $(OBJ_B)

clean:
	@$(REMOVE) $(OBJ) $(OBJ_B)

fclean:	clean
	@$(REMOVE) $(NAME)

re: fclean all

.PHONY: all bonus clean fclean re